### ISSUE TITLE
Permission denied when starting corsproxy.service

### ISSUE THREAD

**Issue by smelehy** [caltechlibrary/corsproxy#2]
I have installed corsproxy on RHEL on AWS.  I am getting permission errors from systemd on starting up of the service.

tail -f on /var/log/messages: shows the following errors

Feb 15 20:07:40 ip-172-31-14-40 systemd[1]: corsproxy.service: Failed to load environment files: Permission denied
Feb 15 20:07:40 ip-172-31-14-40 systemd[1]: corsproxy.service: Failed to run 'start' task: Permission denied
Feb 15 20:07:40 ip-172-31-14-40 systemd[1]: corsproxy.service: Failed with result 'resources'.

It turns out that it is failing in the corsproxy.service file at this line:
EnvironmentFile=/home/corsproxy/admin/config.sh

Here is the strange part.  I have followed the directions exactly, double checked all directory and file ownership and groups, and they are correct per your excellent documentation.  If I move the config.sh file to either root directory or /run/corsproxy directories, the permission error goes away.  The owners, groups and permissions on /run/corsproxy are identical to the ones all the way down the chain with /home/corsproxy/admin, as well as the files themselves.

I have tried everything I can think of on this and cannot figure it out.  There must be something about systemd that I am missing.

**More info:**

If I move config.sh to /run/corsproxy directory, the service will start, but I will get a permission denied at this line:
ExecStart=/home/corsproxy/admin/corsproxy-helper start

This means that the same permission issue applies to corsproxy-helper file as well.  In fact, if i move that file to /run/corsproxy, the permission error goes away, but the script errors out because it is expecting the /home/corsproxy/admin directory structure.

Any suggestions you might have would be greatly appreciated.  I have burned a few days on this so far.  Thank you.

**Comment by mhucka** [comment]
Thanks for the report, and I'm sorry for the trouble it caused. I regret I may not have time to look at this until Thursday (US time) but I will try to figure it out.

**Comment by smelehy** [comment]
Thanks Mike.  Really appreciate it.

 

Sam Melehy

+1 760 39 7216

San Diego, CA

**Comment by mhucka** [comment]
Well, this is mysterious, to say the least. It really sounds like permissions on the directories, but I believe you when you say they all check out. The next possibility that comes to mind is SElinux getting in the way. Assuming that the corsproxy service is not running right now, I would do the following:

1. start a `tail -f /var/log/messages`
2. do `systemctl start corsproxy` (as root)
3. look for anything involving "SELinux" getting printed to `/var/log/messages` right after #2 is issued.

If you do get selinux complaints, then there are two options. One is to figure out how to make selinux happy. I tried in the past for other services but finally gave up, so I personally use the other option, which is to set SElinux into "permissive" mode. [This page](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/changing-selinux-states-and-modes_using-selinux#changing-to-permissive-mode_changing-selinux-states-and-modes) describes the process for RHEL.  

Since I'm using permissive mode, maybe I just never encountered this permissions issue. I think there is probably a way to set SElinux properly, but first I would try to see if making it permissive solves the problem at all. If it does, and you want to use non-permissive SElinux, then some work will be needed to figure out how to do that, but at least the cause of the problem will be identified.

**Comment by smelehy** [comment]
OK, I did a tail on /var/log/messages.  Nothing from SElinux.  I switch to permissive mode per your instructions and the service will now run - no more permission errors.  I can run in permissive mode for now.  Thanks very much

**Comment by mhucka** [comment]
Thanks for the info! I don't know why the messages didn't show in /var/log/messages, although I _am_ running CentOS and  not RHEL proper, so maybe there's a difference due to that. Anyway, I'll add a note about this issue to the instructions. Glad to hear it's resolved.
